routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/',  'HomeController@index')->name('home');
Route::get('/home','HomeController@awal');

Auth::routes();

Route::resource('/post', 'PostController');
Route::resource('/vote', 'VoteController');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function getAgoAttribute()
    {
        return $this->created_at->diffForHumans(null, true) . ' ago';
    }
    public function question()
    {
        return $this->belongsTo('App\Models\Question');
    }

    public function answer()
    {
        return $this->belongsTo('App\Models\Answer');
    }

    public function comment()
    {
        return $this->belongsTo('App\Models\Comment');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function votes()
    {
        return $this->hasMany('App\Models\Vote');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Post;
use App\Models\Artikel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::where('user_id', Auth::user()->id)->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $title = $request->title;
        $content = $request->desc;
        $user = Auth::user()->id;

        $post = Post::create([
            'user_id' => $user,
            'content' => $content,
        ]);

        $post = Artikel::create([
            'title' => $title,
            'post_id' => $post->id,
        ]);

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $artikel = Artikel::where('id', $post->id)->first();
        $post->title = $artikel->title;
        $post->time = $post->ago;
        $post->user = $post->user->name;

        $answers = Answer::with('post')->get();


        return view('post.view', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        // Artikel
        $artikel = Artikel::where('id', $post->post_id)->first();
        $title = $artikel->title;
        return view('post.form', compact('post', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/post/form.blade.php
@extends('layouts.default')
@section('title', 'Buat Artikel')

<?php
    $is_update = isset($post);
    if($is_update) {
        $config['form_title']    = "Ubah Artikel";
        $config['url']          = route('post.update', ['post' => $post->id]);
        $config['method']       = "PUT";
    }else{
        $config['form_title']   = "Buat Artikel Baru";
        $config['url']          = route('post.store');
        $config['method']       = "POST";
    }
?>

@section('content')
<div class='container-fluid'>
    <h1>{{ $config['form_title'] }}</h1>
    <div id='form'>
        <form method="POST" action="{{ $config['url'] }}">
            @csrf
            @method($config['method'])
            <div class="form-group">
                <div class="col">
                    <input 
                        id="title" 
                        type="text" 
                        class="form-control @error('title') is-invalid @enderror" 
                        name="title" 
                        value="{{ old('title', isset($title) ? $title : '') }}" 
                        required 
                        placeholder="Judul"
                        autocomplete="title" 
                        autofocus
                    />
    
                    @error('title')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
    
            <div class="form-group">
                <div class="col">
                    <textarea 
                        id="desc" 
                        class="form-control @error('desc') is-invalid @enderror" 
                        name="desc" 
                        hidden
                        required 
                        placeholder="Tuliskan Artikel disini..."
                        autocomplete="title" 
                        autofocus
                    >
                        {{ old('desc', $is_update ? $post->content : '') }}
                    </textarea>
    
                    @error('desc')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
    
            <div class="form-group">
                <div class='col'>
                    <button class="btn btn-primary">
                        Tambahkan
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div id='preview'>
        
    </div>
</div>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
    tinymce.init({selector:'#desc'});

    var preview_btn = document.getElementById('preview_btn');
    preview_btn.addEventListener('click', function(e) {
        e.preventDefault();

        var title = document.getElementById('title').value;
        var desc  = document.getElementById('desc').value;

        console.log(title, desc);
    });
</script>
@endsection

resources/views/post/view.blade.php
<?php
    $content = $post->title;
    $desc    = $post->content;
    $vote    = 0;
    $by      = $post->user;
    $time    = $post->time;
?>

@extends('layouts.default')
@section('title', "Halaman Artikel {$content}")

@section('content')
<div class='container-fluid pb-5'>
    <div class='row'>
        <div class='col-1'>
            <div class='d-flex flex-column'>
                <div class="text-center">
                    <a href="#" style="font-size:40px;" >
                        <i class="fas fas-xl fa-caret-up"></i>
                    </a>
                </div>
                <div class="font-weight-bold h4 text-center">
                    {{ $vote }}
                </div>
                <div class="text-center">
                    <a href="#" style="font-size:40px;" >
                        <i class="fas fa-caret-down"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-11">
            <h1>{{ $content }}</h1>
            <div>
                {!! $desc !!}
            </div>
            <div>
                <sub>
                    {{ $by }} at {{ $time }} <br />
                    @if(Auth::user())
                        @if(Auth::user()->id == $post->user_id)
                            <a href="{{ route('post.edit', ['post' => $post->id ]) }}">Ubah</a>
                        @endif
                    @endif
                </sub>
            </div>
        </div>
    </div>
</div>

<div class='container-fluid'>
    <div class='row'>
        <div class='col'>
            <h3>Komentar</h3>
            <hr class="sidebar-divider">
        </div>
    </div>
    <div class='row'>
        <div class='col-1'>
            <div class='d-flex flex-column'>
                <div class="text-center">
                    <a href="#" style="font-size:40px;" >
                        <i class="fas fas-xl fa-caret-up"></i>
                    </a>
                </div>
                <div class="font-weight-bold h4 text-center">
                    {{ $vote }}
                </div>
                <div class="text-center">
                    <a href="#" style="font-size:40px;" >
                        <i class="fas fa-caret-down"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-11">
            <div>
                {!! $desc !!}
            </div>
            <div>
                <sub>
                    {{ $by }} at {{ $time }}
                </sub>
            </div>
        </div>
    </div>
</div>
@endsection